builds: 
  -
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archive:
  replacements:
    darwin: macOS
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
